Updated readme.md to include the Entity-Relationship Diagram
JavaHate/Math-Master-Info pull request #2
Opened 2024-09-23 15:48 UTC by Matas5

Updated readme.md to include the Entity-Relationship Diagram using Mermaid.js

2024-09-23 16:17 UTC, ValdemarKobelis approved these changes

2024-09-23 16:17 UTC, ValdemarKobelis commented on readme.md
> +    leaderboard {
🙈

2024-09-24 06:57 UTC, dzeveckij approved these changes
ye, dont need leaderboard

2024-09-24 14:32 UTC, dzeveckij requested changes
Leader board

2024-09-24 14:44 UTC, dzeveckij approved these changes

2024-09-24 14:44 UTC, merged